rohitpythony/app/asset/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField
from wtforms.ext.sqlalchemy.fields import QuerySelectField
from wtforms.validators import DataRequired

from ..models import Asset


class AssetForm(FlaskForm):
    """
    Form for user to add to edit his Assets
    """
    comments = StringField('Comments', validators=[DataRequired()])
    submit = SubmitField('Submit')

rohitpythony/app/asset/__init__.py
# app/assets/__init__.py

from flask import Blueprint

asset = Blueprint('assets', __name__)

from . import views

rohitpythony/app/asset/views.py
from flask import abort, flash, redirect, render_template, url_for
from flask_login import current_user, login_required

from . import asset

from forms import AssetForm
from .. import db
from ..models import Asset,Inventory,Location

# asset Views


@asset.route('/assets', methods=['GET', 'POST'])
@login_required
def list_assets():
    """
    List all departments
    """
    assets = current_user.assets #Asset.query.all()

    return render_template('assets/assets.html',
                           assets=assets, title="Assets")


@asset.route('/assets/add', methods=['GET', 'POST'])
@login_required
def add_asset():
    """
    Add a asset to the database
    """

    add_asset = True

    form = AssetForm()
    if form.validate_on_submit():
        asset = Asset(comments=form.comments.data,
            inventory_id=Inventory.query.first().id,
            location=Location.query.first().id,
            managed_by=current_user.id,
            assigned_to=current_user.id,
            certified_by=current_user.id,
             )
        try:
            # add asset to the database
            db.session.add(asset)
            db.session.commit()
            flash('You have successfully added a new Asset.')
        except:
            # in case asset name already exists
            flash('Error: Asset cannot be created.')

        # redirect to assets page
        return redirect(url_for('assets.list_assets'))

    # load department template
    return render_template('assets/asset.html', action="Add",
                           add_asset=add_asset, form=form,
                           title="Add Asset")


@asset.route('/assets/edit/<int:id>', methods=['GET', 'POST'])
@login_required
def edit_asset(id):
    """
    Edit an asset
    """

    add_asset = False

    asset = Asset.query.get_or_404(id)
    form = AssetForm(obj=asset)
    if form.validate_on_submit():
        asset.comments = form.comments.data
        db.session.commit()
        flash('You have successfully edited the asset.')

        # redirect to the departments page
        return redirect(url_for('assets.list_assets'))

    return render_template('assets/asset.html', action="Edit",
                           add_asset=add_asset, form=form,
                           asset=asset, title="Edit Asset")


@asset.route('/assets/delete/<int:id>', methods=['GET', 'POST'])
@login_required
def delete_asset(id):
    """
    Delete a department from the database
    """

    asset = Asset.query.get_or_404(id)
    db.session.delete(asset)
    db.session.commit()
    flash('You have successfully deleted the asset.')

    # redirect to the departments page
    return redirect(url_for('assets.list_assets'))

    return render_template(title="Delete Asset")

rohitpythony/app/templates/assets/asset.html
{% import "bootstrap/wtf.html" as wtf %}
{% extends "base.html" %}
{% block title %}
    {% if add_asset %}
        Add Asset
    {% else %}
        Edit Asset
    {% endif %}
{% endblock %}
{% block body %}
<div class="content-section">
 <div class="outer">
    <div class="middle">
      <div class="inner">
        <div class="center">
            {% if add_asset %}
                <h1>Add Asset</h1>
            {% else %}
                <h1>Edit Asset</h1>
            {% endif %}
            <br/>
            {{ wtf.quick_form(form) }}
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

rohitpythony/app/templates/assets/assets.html
{% import "bootstrap/utils.html" as utils %}
{% extends "base.html" %}
{% block title %}Assets{% endblock %}
{% block body %}
<div class="content-section">
  <div class="outer">
    <div class="middle">
      <div class="inner">
        <br/>
        {{ utils.flashed_messages() }}
        <br/>
        <h1 style="text-align:center;">Assets</h1>
        {% if assets %}
          <hr class="intro-divider">
          <div class="center">
            <table class="table table-striped table-bordered">
              <thead>
                <tr>
                  <th width="40%"> comments </th>
                  <th width="15%"> Managed_by</th>
                  <th width="15%"> location</th>
                  <th width="15%"> Edit </th>
                  <th width="15%"> Delete </th>
                </tr>
              </thead>
              <tbody>
              {% for asset in assets %}
                <tr>
                  <td> {{ asset.comments }} </td>
                  <td> {{ asset.user_assets.name }} </td>
                  <td> {{ asset.location_assets.description }} </td>

                  
                  <td>
                    <a href="{{ url_for('assets.edit_asset', id=asset.id) }}">
                      <i class="fa fa-pencil"></i> Edit
                    </a>
                  </td>
                  <td>
                    <a href="{{ url_for('assets.delete_asset', id=asset.id) }}">
                      <i class="fa fa-trash"></i> Delete
                    </a>
                  </td>
                </tr>
              {% endfor %}
              </tbody>
            </table>
          </div>
          <div style="text-align: center">
        {% else %}
          <div style="text-align: center">
            <h3> No assets have been added. </h3>
            <hr class="intro-divider">
        {% endif %}
          <a href="{{ url_for('assets.add_asset') }}" class="btn btn-default btn-lg">
            <i class="fa fa-plus"></i>
            Add Asset
          </a>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}