rohitpythony/app/home/__init__.py
# app/home/__init__.py

from flask import Blueprint

home = Blueprint('home', __name__)

from . import views

rohitpythony/app/home/views.py
from flask import render_template
from flask_login import login_required

from . import home


@home.route('/')
def homepage():
    """
    Render the homepage template on the / route
    """
    return render_template('home/index.html', title="Welcome")


@home.route('/dashboard')
@login_required
def dashboard():
    """
    Render the dashboard template on the /dashboard route
    """
    return render_template('home/dashboard.html', title="Dashboard")

rohitpythony/app/templates/home/dashboard.html
{% extends "base.html" %}
{% block title %}Dashboard{% endblock %}
{% block body %}
<div class="intro-header">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <div class="intro-message">
                    <h1>Mercury Wireless Dashboard</h1>
                    <h3>CRUD for Assets Entity!</h3>
                    <hr class="intro-divider">
                    <a href="{{ url_for('assets.list_assets') }}" class="btn btn-lg btn-success">Assets Index</a>
                     
                    </ul>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

rohitpythony/app/templates/home/index.html
{% extends "base.html" %}
{% block title %}Home{% endblock %}
{% block body %}
<div class="intro-header">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <div class="intro-message">
                    <h1>Mercury Wireless</h1>
                    <hr class="intro-divider">
                    {% if current_user.is_authenticated %}
                    <a class="btn btn-lg btn-success" href="{{ url_for('home.dashboard') }}">Go to Dashboard</a>
                    {% else %}
                    <a class="btn btn-lg btn-success" href=                          "{{ url_for('auth.login') }}">Login</a>
                    <a class="btn btn-lg btn-danger" href="{{ url_for('auth.register') }}">Register</a>
                    {% endif %}
                    </ul>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}